version: '3'
services:
  web:
    image: docker-node-mongo
    build: .
    command: "node server.js"
    ports:
      - "3000:3000"
    env_file:
      - app-variables.env
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
